### ISSUE TITLE
Poste.io

### ISSUE THREAD

**Issue by Neustradamus** [analogic/ipgeo#2]
@analogic: It is possible to add Poste.io in GitHub?

Thanks in advance.

**Comment by IndrajeethY** [comment]
++ also hey there cant i customize the self hosted mail server from [poste.io](https://poste.io/). Like editing some front end stuffs. Also isnt there any way to set custom name for mail ids instead of using domain name as name.

**Comment by analogic** [comment]
Sorry guys, this is not right place to fill issue with poste.io
